### PR TITLE
Improvement/refactor game engine

### PR DESCRIPTION
**Pull request by stevenkhong**
This branch includes: 
- feature/wormhole
- feature/actionToJSON

Mostly refactoring GameEngine to handle multiplayer mode. Added some documentation and some other refactoring on other files.

Current State: Multiplayer should be playable, though I can't seem to get 100% steady start when I try with simulator + my iPad. Always had to exit LobbyView and then back again few times before game will start. Movement is fixed, cats don't combine into one stacked cat anymore. However there is a problem turn synchronization in the current implementation: #36

### CODE REVIEW

**Comment by junhaoyap** [comment]
@justwudi take a look too

**Comment by justwudi** [comment]
I did. I even branched off to make the game manager class.

On 9 April, 2015 at 11:58:19 pm, Yap Jun Hao (notifications@github.com) wrote:

@justwudi take a look too

**Comment by junhaoyap** [comment]
Ohh, ok, swee! You still awake now ah?:o

**Comment by stevenkhong** [comment]
Multiplayer is stable now, except for turn synchronization. so often movement displayed is one turn before actual. Maybe we can do a "check for all movement submitted" before advancing a turn.

Shall we merge?

**Note: Currently game starts at 2 players, need not add unnecessary uncertainties with 4 players until we get 2 players stable enough.**

**Comment by justwudi** [comment]
Resolved #30

**Pull request merged**
